language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
  - "3.6"
  - "3.7‚Äù
env:
  # TODO: add test env (where DEBUG=False, secret key unencrypted)
  - HKNWEB_MODE=dev
install:
  # Dependencies
  - pip install pipenv
  - pipenv install
  # Dev dependencies
  - pipenv install --dev
script:
  - pipenv run python ./manage.py migrate
  - pipenv run python ./manage.py check
