name: hknweb-dev
dependencies:
  - python=3.9
  - pip
  - pip:
    - -r requirements.txt
    - livereload==2.6.0
    - coverage[toml]==6.3.2
    - black==22.3.0
variables:
  HKNWEB_MODE: "dev"
  DJANGO_SETTINGS_MODULE: "hknweb.settings"
